version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    network_mode: host
    volumes:
      - /home/idan/jenkins1:/var/jenkins_home
      
  tomcat:
    image: tomcat:8.0
    ports:
      - "8888:8080"
    container_name: tomcat
    volumes:
      - /home/idan/jenkins1:/usr/local/tomcat/webapps/status
